theme: jekyll-theme-hacker
description: 'The Official Defcon Group of the Upstate South Carolina'

url: https://www.dc864.org
title: DC864
github: [metadata]
email: DEFCON864info@gmail.com
plugins:
  - jekyll-paginate
  - jekyll-sitemap

google_analytics: UA-139997393-1

# Permalinks
permalink: :title:output_ext

# Support for tagging
tag_page: '/blog/tags/'
category_page: '/blog/categories/'