theme: jekyll-theme-hacker
url: https://www.dc864.org
title: DC864
github: [metadata]
plugins:
  - jekyll-paginate
  - jekyll-sitemap

google_analytics: UA-139997393-1

# Permalinks
permalink: :title:output_ext